services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Exponer el puerto 3000
    environment:
      - REACT_APP_API_URL=http://backend:8080/api/v1/smartphones # URL de la API del backend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Exponer el puerto 8080
    volumes:
      - ./backend:/app # Montar el directorio del backend para reflejar cambios
    environment:
      - DATABASE_URL=mongodb://mongo:27017/mydb # Cambia esto según tu base de datos
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Exponer el puerto de MongoDB
